services:
  app:
    container_name: xdaemon-app
    build: .
    ports:
      - '5002:3000'
    environment:
      NODE_ENV: production
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
    volumes:
      - ./logs:/app/logs
