version: "3.8"

services:
  app:
    container_name: md2pdf-app
    build: .
    env_file:
      - .env
    ports:
      - "5001:5001"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./logs:/app/logs
